In [3]:
import tensorflow as tf

In [4]:
tf.__version__

'2.3.0'

In [5]:
# 创建tensor
x=tf.constant(range(12))

In [6]:
x

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])>

In [7]:
x.shape

TensorShape([12])

In [8]:
len(x)

12

In [12]:
tf.reshape(x,[3,4])

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [13]:
tf.zeros((3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [14]:
tf.ones([2,3,4])

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [19]:
a=tf.constant([[2,3,4],[3,4,5],[4,5,6]])
b=tf.constant([[2,3,4],[3,4,5],[4,5,6]])

In [17]:
tf.random.normal(shape=[3,4],mean=0,stddev=1)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.34848273,  0.25003985, -0.5576707 ,  0.4475031 ],
       [ 0.1234291 , -1.5922319 , -0.4467399 , -1.079836  ],
       [ 0.01208241, -0.8322092 , -0.47977123,  1.3268423 ]],
      dtype=float32)>

In [18]:
# 运算

In [20]:
a+b

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 4,  6,  8],
       [ 6,  8, 10],
       [ 8, 10, 12]])>

In [22]:
a/b

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])>

In [23]:
a*b

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 4,  9, 16],
       [ 9, 16, 25],
       [16, 25, 36]])>

In [24]:
a-b

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])>

In [38]:
a=tf.cast(a,tf.float32)

In [39]:
tf.exp(a)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[  7.389056,  20.085537,  54.598152],
       [ 20.085537,  54.598152, 148.41316 ],
       [ 54.598152, 148.41316 , 403.4288  ]], dtype=float32)>

In [43]:
a=tf.cast(a,tf.int32)
a=tf.transpose(a)
a,b

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])>)

In [41]:
tf.matmul(b,tf.transpose(a))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[29, 38, 47],
       [38, 50, 62],
       [47, 62, 77]])>

In [44]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(6, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])>

In [45]:
tf.concat([a,b],axis=1)

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[2, 3, 4, 2, 3, 4],
       [3, 4, 5, 3, 4, 5],
       [4, 5, 6, 4, 5, 6]])>

In [46]:
tf.equal(a,b)

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

In [47]:
tf.reduce_sum(a)

<tf.Tensor: shape=(), dtype=int32, numpy=36>

In [48]:
tf.reduce_min(a)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [49]:
tf.reduce_mean(a)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [61]:
a=tf.cast(a,tf.float32)
# 2范数函数
tf.norm(a)

<tf.Tensor: shape=(), dtype=float32, numpy=12.489996>

In [62]:
# 2范数手动实现
t=tf.reduce_sum(a*a)
tf.sqrt(t)

<tf.Tensor: shape=(), dtype=float32, numpy=12.489996>

In [63]:
# 广播机制

In [64]:
m=tf.constant(tf.reshape(tf.range(3),[3,1]))
n=tf.constant(tf.reshape(tf.range(2),[1,2]))

In [65]:
m,n

(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]])>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]])>)

In [67]:
#由于A和B分别是3行1列和1行2列的矩阵，如果要计算A + B，那么A中第一列的3个元素被广播（复制）到了第二列，
#而B中第一行的2个元素被广播（复制）到了第二行和第三行。如此，就可以对2个3行2列的矩阵按元素相加。
m+n

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]])>

In [68]:
# 索引
a[1:3]

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[3., 4., 5.],
       [4., 5., 6.]], dtype=float32)>

In [71]:
a[1:3][1]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 5., 6.], dtype=float32)>

In [72]:
a[1:3][1][0]

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [73]:
a=tf.Variable(a)
a[1,2].assign(0)

<tf.Variable 'UnreadVariable' shape=(3, 3) dtype=float32, numpy=
array([[2., 3., 4.],
       [3., 4., 0.],
       [4., 5., 6.]], dtype=float32)>

In [79]:
a=tf.Variable(a)
a[1:3,:].assign(tf.ones(a[1:3,:].shape)*12)

<tf.Variable 'UnreadVariable' shape=(3, 3) dtype=float32, numpy=
array([[ 2.,  3.,  4.],
       [12., 12., 12.],
       [12., 12., 12.]], dtype=float32)>

In [95]:
# 运算的内存开销
# 使用Python自带的id函数：如果两个实例的ID一致，那么它们所对应的内存地址相同；反之则不同
before=id(a)
before

2758745227328

In [96]:
b=tf.cast(b,tf.float32)
a=a+b
before==id(a)

False

In [97]:
id(a)

2758745228032

In [100]:
c=tf.zeros_like(a)
c[:].assign(a+b)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [102]:
c=tf.Variable(tf.zeros_like(a))
iiiid=id(c)
c[:].assign(a+b)
iiiid==id(c)

True

In [105]:
# 实际上，上例中我们还是为a+ b开了临时内存来存储计算结果，再复制到c对应的内存。
# 如果想避免这个临时内存开销，我们可以使用assign_{运算符全名}函数。
a=tf.Variable(a)
ida=id(a)
a.assign_add(b)
ida==id(a)
#如果a的值在之后的程序中不会复用，我们也可以用 a[:] = a+ b或者 a += b 来减少运算的内存开销。

True

In [108]:
# tensor 和 NumPy 相互变换
#我们可以通过array函数和asnumpy函数令数据在NDArray和NumPy格式之间相互变换
import numpy as np

p=np.ones((2,3))
p

array([[1., 1., 1.],
       [1., 1., 1.]])

In [109]:
d=tf.constant(p)
d

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [110]:
np.array(d)

array([[1., 1., 1.],
       [1., 1., 1.]])